// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAegMJdraTD1jt0U3tzRyfbe1ZCkw6GVVA',
    appId: '1:307944058057:web:07c98f0c74185a2c88f118',
    messagingSenderId: '307944058057',
    projectId: 'laggytodolist',
    authDomain: 'laggytodolist.firebaseapp.com',
    storageBucket: 'laggytodolist.firebasestorage.app',
    measurementId: 'G-4PQ3KC5YKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6rzBTW_USYJ5wstiU-mcFoot5QB8kcE',
    appId: '1:307944058057:android:5cc9805b5c9af3b188f118',
    messagingSenderId: '307944058057',
    projectId: 'laggytodolist',
    storageBucket: 'laggytodolist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7gzN52FSXKEz_Qw3lGq0kKZyWgMuzNeQ',
    appId: '1:307944058057:ios:4cb55e8d78a0dcb688f118',
    messagingSenderId: '307944058057',
    projectId: 'laggytodolist',
    storageBucket: 'laggytodolist.firebasestorage.app',
    iosClientId: '307944058057-o2ark2uaqtocf40hckho6outjhtv7mis.apps.googleusercontent.com',
    iosBundleId: 'com.example.laggytodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7gzN52FSXKEz_Qw3lGq0kKZyWgMuzNeQ',
    appId: '1:307944058057:ios:4cb55e8d78a0dcb688f118',
    messagingSenderId: '307944058057',
    projectId: 'laggytodolist',
    storageBucket: 'laggytodolist.firebasestorage.app',
    iosClientId: '307944058057-o2ark2uaqtocf40hckho6outjhtv7mis.apps.googleusercontent.com',
    iosBundleId: 'com.example.laggytodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAegMJdraTD1jt0U3tzRyfbe1ZCkw6GVVA',
    appId: '1:307944058057:web:ec37a5cd8502d09888f118',
    messagingSenderId: '307944058057',
    projectId: 'laggytodolist',
    authDomain: 'laggytodolist.firebaseapp.com',
    storageBucket: 'laggytodolist.firebasestorage.app',
    measurementId: 'G-G4P7RC7B21',
  );
}
